services:
  - type: web
    name: cerasync-back
    runtime: docker
    plan: free
    region: frankfurt
    buildCommand: docker build -t cerasync-back .
    startCommand: docker run -p $PORT:8080 cerasync-back
    envVars:
      - key: JDBC_DATABASE_URL
        sync: false
      - key: JDBC_DATABASE_USERNAME
        sync: false
      - key: JDBC_DATABASE_PASSWORD
        sync: false
      - key: JWT_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: PORT
        value: 8080